const mongoose = require('mongoose');

const resumeSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true
  },
  title: {
    type: String,
    required: true
  },
  data: {
    fullName: String,
    jobRole: String,
    email: String,
    phone: String,
    location: String,
    portfolio: String,
    careerGoal: String,
    workExperience: String,
    skills: String,
    education: String,
    projects: String
  },
  content: {
    type: String, // The actual resume content generated by the AI
    required: false  // Changed from true to false since it might be populated later
  },
  template: {
    type: String,
    default: 'default'
  },
  status: {
    type: String,
    enum: ['draft', 'completed'],
    default: 'completed'
  }
}, {
  timestamps: true
});

module.exports = mongoose.model('Resume', resumeSchema);